from django.shortcuts import render                     # Import render (not used but standard import)
from django.contrib.auth.models import User             # Import Django's built-in User model
from rest_framework import generics                     # Import DRF generic view classes
from .serializers import UserSerializer, NoteSerializer # Import serializers for User and Note
from rest_framework.permissions import IsAuthenticated, AllowAny  # Import permission classes
from .models import Note                                # Import Note model for database operations


# Create your views here.                             # Standard Django comment generated by default


class NoteListCreate(generics.ListCreateAPIView):       # View for listing notes (GET) and creating notes (POST)
    serializer_class = NoteSerializer                   # Use NoteSerializer to convert data to/from JSON
    permission_classes = [IsAuthenticated]              # Require user to be logged in to access this view

    def get_queryset(self):                             # Function to define which notes this user can access
        user = self.request.user                        # Get the logged-in user from the request
        return Note.objects.filter(author=user)         # Return only notes created by this user
    
    def perform_create(self, serializer):               # Function that runs when a new note is created
        if serializer.is_valid():                       # Check if incoming data matches serializer validation
            serializer.save(author=self.request.user)   # Save note with logged-in user as author
        else:                                           # If serializer is not valid
            print(serializer.errors)                    # Print validation errors to console for debugging


class NoteDelete(generics.DestroyAPIView):              # View for deleting a specific note (DELETE request)
    serializer_class = NoteSerializer                   # Use NoteSerializer (required even for delete)
    permission_classes = [IsAuthenticated]              # Only authenticated users can delete notes

    def get_queryset(self):                             # Function to select which notes can be deleted
        user = self.request.user                        # Get current logged-in user
        return Note.objects.filter(author=user)         # User can delete only their own notes


class createUserView(generics.CreateAPIView):           # View for creating a new user (POST request)
    queryset = User.objects.all()                       # Base queryset (not used but required by DRF)
    serializer_class = UserSerializer                   # Use UserSerializer to create and validate users
    permission_classes = [AllowAny]                     # Anyone can sign up (no authentication needed)
